create extension if not exists pgcrypto;

create table if not exists customers (
  id uuid primary key,
  code text not null unique,
  cnpj text,
  state_tax_id text,
  taxpayer integer not null default 0,
  name text not null,
  trade_name text,
  seller text default 'VANDO',
  cep text,
  street text,
  number text,
  complement text,
  neighborhood text,
  city text,
  uf text,
  city_code text,
  country text,
  country_code text,
  phone text,
  email text,
  home_page text,
  tracks_orders integer not null default 0,
  registered_at text,
  last_updated_at text,
  blocked integer not null default 0,
  block_reason text,
  customer_type_code text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists products (
  id uuid primary key,
  reference text not null unique,
  tele_ref text,
  barcode text,
  gtin text,
  description text not null,
  composition text,
  unit text not null default 'UN',
  kind text not null default 'UNKNOWN',
  price double precision,
  cost double precision,
  min_stock double precision,
  stock_qty double precision not null default 0,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table if not exists product_recipes (
  product_id uuid not null,
  input_product_id uuid not null,
  quantity double precision not null,
  created_at text not null default (current_timestamp::text),
  primary key (product_id, input_product_id),
  foreign key (product_id) references products(id) on delete cascade,
  foreign key (input_product_id) references products(id) on delete restrict
);

create index if not exists idx_product_recipes_product on product_recipes(product_id);
create index if not exists idx_product_recipes_input on product_recipes(input_product_id);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references customers(id) on delete restrict,
  status text not null default 'PENDING',
  payment_method text not null default 'BOLETO',
  notes text,
  issued_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id uuid primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  quantity double precision not null,
  unit_price double precision,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_items_order_id on order_items(order_id);
create index if not exists idx_order_items_product_id on order_items(product_id);

create table if not exists invoices (
  id uuid primary key,
  order_id bigint not null references orders(id) on delete cascade,
  status text not null default 'DRAFT',
  number text,
  invoice_key text,
  issued_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_invoices_order_id on invoices(order_id);

create table if not exists receivables (
  id uuid primary key,
  customer_id uuid not null references customers(id) on delete restrict,
  order_id bigint references orders(id) on delete set null,
  status text not null default 'OPEN',
  method text not null default 'BOLETO',
  amount double precision not null,
  due_date timestamptz not null,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_receivables_customer_due on receivables(customer_id, due_date);
create index if not exists idx_receivables_order_id on receivables(order_id);

create table if not exists boletos (
  id uuid primary key,
  receivable_id uuid not null unique references receivables(id) on delete cascade,
  payload_json text not null,
  created_at timestamptz not null default now()
);

create table if not exists cash_movements (
  id uuid primary key,
  kind text not null,
  source_type text not null,
  source_id text not null,
  method text,
  amount double precision not null,
  effective_date timestamptz not null,
  note text,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_cash_movements_source_kind on cash_movements(source_type, source_id, kind);

create table if not exists loadings (
  id uuid primary key,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists loading_orders (
  loading_id uuid not null references loadings(id) on delete cascade,
  order_id bigint not null references orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (loading_id, order_id)
);

create index if not exists idx_loading_orders_loading on loading_orders(loading_id);
create index if not exists idx_loading_orders_order on loading_orders(order_id);

create table if not exists production_orders (
  id uuid primary key,
  notes text,
  status text not null default 'OPEN',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists production_order_products (
  production_order_id uuid not null references production_orders(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  quantity double precision not null,
  created_at timestamptz not null default now(),
  primary key (production_order_id, product_id)
);

create index if not exists idx_production_order_products_order on production_order_products(production_order_id);
create index if not exists idx_production_order_products_product on production_order_products(product_id);

create table if not exists production_order_inputs (
  production_order_id uuid not null references production_orders(id) on delete cascade,
  input_product_id uuid not null references products(id) on delete restrict,
  total_quantity double precision not null,
  created_at timestamptz not null default now(),
  primary key (production_order_id, input_product_id)
);

create index if not exists idx_production_order_inputs_order on production_order_inputs(production_order_id);
create index if not exists idx_production_order_inputs_input on production_order_inputs(input_product_id);

create table if not exists purchase_invoices (
  id uuid primary key,
  supplier_name text,
  number text,
  issued_at timestamptz,
  status text not null default 'POSTED',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists purchase_invoice_items (
  id uuid primary key,
  purchase_invoice_id uuid not null references purchase_invoices(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  quantity double precision not null,
  unit_cost double precision not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_purchase_invoice_items_invoice on purchase_invoice_items(purchase_invoice_id);
create index if not exists idx_purchase_invoice_items_product on purchase_invoice_items(product_id);

create table if not exists payables (
  id uuid primary key,
  purchase_invoice_id uuid references purchase_invoices(id) on delete set null,
  supplier_name text,
  status text not null default 'PENDING',
  method text not null default 'BOLETO',
  amount double precision not null,
  due_date timestamptz not null,
  paid_at timestamptz,
  payment_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_payables_due_status on payables(due_date, status);
create index if not exists idx_payables_invoice_id on payables(purchase_invoice_id);

create table if not exists stock_movements (
  id uuid primary key,
  product_id uuid not null references products(id) on delete cascade,
  type text not null,
  quantity double precision not null,
  unit_cost double precision,
  reason_code text,
  note text,
  reason text,
  order_id bigint references orders(id) on delete set null,
  production_order_id uuid references production_orders(id) on delete set null,
  purchase_invoice_id uuid references purchase_invoices(id) on delete set null,
  meta_json text,
  created_at timestamptz not null default now()
);

create index if not exists idx_stock_movements_product_created on stock_movements(product_id, created_at);
create index if not exists idx_stock_movements_order_id on stock_movements(order_id);

create table if not exists route_weeks (
  id uuid primary key,
  week_start date not null unique,
  created_at timestamptz not null default now()
);

create table if not exists route_entries (
  id uuid primary key,
  route_week_id uuid not null references route_weeks(id) on delete cascade,
  weekday integer not null,
  customer_id uuid not null references customers(id) on delete restrict,
  status text not null default 'NONE',
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_route_entries_week_day on route_entries(route_week_id, weekday, sort_order);
create index if not exists idx_route_entries_customer on route_entries(customer_id);

create table if not exists fiscal_migrations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sha256 text not null,
  applied_at timestamptz not null default now()
);

create table if not exists fiscal_product_fiscal_data (
  product_id uuid primary key references products(id) on delete cascade,
  ncm varchar(8) not null,
  cest varchar(7),
  origem smallint not null,
  unidade_tributavel varchar(6) not null,
  cst_icms varchar(3) not null,
  cst_pis varchar(2) not null,
  cst_cofins varchar(2) not null,
  aliquota_icms numeric(7,4),
  aliquota_pis numeric(7,4),
  aliquota_cofins numeric(7,4),
  cfop_padrao varchar(4) not null,
  beneficios_fiscais jsonb not null default '[]'::jsonb,
  tributacao_interna jsonb not null default '{}'::jsonb,
  tributacao_interestadual jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists fiscal_profiles (
  id text primary key,
  code text not null unique,
  name text not null,
  description text,
  rules jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists fiscal_operations (
  id text primary key,
  code text not null unique,
  natureza_operacao text not null,
  cfop varchar(4) not null,
  tipo_documento smallint not null,
  finalidade_emissao smallint not null,
  local_destino smallint not null,
  consumidor_final boolean not null default false,
  devolucao boolean not null default false,
  bonificacao boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists fiscal_sequences (
  issuer_cnpj varchar(14) not null,
  model int not null,
  serie varchar(3) not null,
  next_number int not null,
  updated_at timestamptz not null default now(),
  primary key (issuer_cnpj, model, serie)
);

create table if not exists fiscal_invoices (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issuer_cnpj varchar(14) not null,
  customer_id uuid not null references customers(id) on delete restrict,
  model int not null,
  serie varchar(3) not null,
  numero int,
  internal_status text not null,
  focus_ref text unique,
  focus_status text,
  sefaz_status text,
  sefaz_message text,
  chave_acesso varchar(44),
  protocolo_autorizacao text,
  xml_authorized text,
  danfe_pdf_path text
);

create index if not exists fiscal_invoices_issuer_model_serie_numero_idx
  on fiscal_invoices (issuer_cnpj, model, serie, numero);

create table if not exists fiscal_events (
  id text primary key,
  invoice_id text not null references fiscal_invoices(id) on delete cascade,
  type text not null,
  version int not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (invoice_id, version)
);

create table if not exists fiscal_jobs (
  id text primary key,
  kind text not null,
  status text not null,
  attempts int not null default 0,
  run_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  last_error text,
  invoice_id text references fiscal_invoices(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fiscal_jobs_status_run_at_idx on fiscal_jobs (status, run_at);
